<?php

namespace App\Models;
use CodeIgniter\Model;

class LoaModel extends Model
{
    protected $table = 'loas';
    protected $primaryKey = 'id';
    protected $returnType = 'array';
    protected $allowedFields = [
        'registration_id', 'loa_number', 'file_path', 'upload_type', 'generated_by', 'generated_at'
    ];

    protected $useTimestamps = false;

    /**
     * Generate LOA for presenter after payment completion
     */
    public function generatePresenterLoa($registrationId, $generatedBy)
    {
        // Check if LOA already exists
        $existingLoa = $this->where('registration_id', $registrationId)->first();
        if ($existingLoa) {
            return $existingLoa;
        }

        // Generate unique LOA number
        $loaNumber = $this->generateLoaNumber($registrationId);

        // Create LOA record (file will be generated later)
        $data = [
            'registration_id' => $registrationId,
            'loa_number' => $loaNumber,
            'file_path' => '', // Will be updated after PDF generation
            'upload_type' => 'admin', // Generated by system
            'generated_by' => $generatedBy,
            'generated_at' => date('Y-m-d H:i:s')
        ];

        $loaId = $this->insert($data);
        
        if ($loaId) {
            // Generate PDF and update file path
            $filePath = $this->generateLoaPdf($loaId, $registrationId, $loaNumber);
            if ($filePath) {
                $this->update($loaId, ['file_path' => $filePath]);
                return $this->find($loaId);
            }
        }

        return false;
    }

    /**
     * Generate unique LOA number
     */
    private function generateLoaNumber($registrationId)
    {
        $year = date('Y');
        $month = date('m');
        
        // Format: LOA-YYYY-MM-XXXX
        $prefix = "LOA-{$year}-{$month}";
        
        // Get last LOA number for this month
        $lastLoa = $this->like('loa_number', $prefix)
                       ->orderBy('id', 'DESC')
                       ->first();
        
        if ($lastLoa) {
            $lastNumber = (int) substr($lastLoa['loa_number'], -4);
            $newNumber = $lastNumber + 1;
        } else {
            $newNumber = 1;
        }
        
        return $prefix . '-' . str_pad($newNumber, 4, '0', STR_PAD_LEFT);
    }

    /**
     * Generate LOA PDF document
     */
    private function generateLoaPdf($loaId, $registrationId, $loaNumber)
    {
        try {
            // Get registration details
            $db = \Config\Database::connect();
            $registration = $db->table('registrations r')
                ->select('r.*, u.first_name, u.last_name, u.email, u.affiliation, e.title as event_title, e.start_date, e.end_date, e.location')
                ->join('users u', 'u.id = r.user_id', 'inner')
                ->join('events e', 'e.id = r.event_id', 'inner')
                ->where('r.id', $registrationId)
                ->get()->getFirstRow('array');

            if (!$registration) {
                return false;
            }

            // Get accepted abstract
            $abstract = $db->table('abstracts a')
                ->select('a.title as abstract_title, a.abstract_text, a.keywords')
                ->where('a.registration_id', $registrationId)
                ->where('a.review_status', 'accepted')
                ->get()->getFirstRow('array');

            // Create uploads directory if not exists
            $uploadPath = WRITEPATH . 'uploads/loa/';
            if (!is_dir($uploadPath)) {
                mkdir($uploadPath, 0755, true);
            }

            // Generate PDF file name
            $fileName = 'LOA_' . $loaNumber . '_' . time() . '.pdf';
            $filePath = $uploadPath . $fileName;

            // Generate PDF content (simple HTML to PDF for now)
            $htmlContent = $this->generateLoaHtml($registration, $abstract, $loaNumber);
            
            // Save as HTML for now (in production, use PDF library like TCPDF or mPDF)
            file_put_contents($filePath . '.html', $htmlContent);
            
            return 'uploads/loa/' . $fileName . '.html';

        } catch (\Exception $e) {
            log_message('error', 'Generate LOA PDF error: ' . $e->getMessage());
            return false;
        }
    }

    /**
     * Get LOA by registration ID
     */
    public function getLoaByRegistration($registrationId)
    {
        return $this->where('registration_id', $registrationId)->first();
    }

    /**
     * Check if presenter can download LOA (payment completed)
     */
    public function canDownloadLoa($registrationId)
    {
        $db = \Config\Database::connect();
        
        // Check if payment is completed
        $payment = $db->table('payments')
            ->where('registration_id', $registrationId)
            ->where('payment_status', 'success')
            ->get()->getFirstRow('array');
            
        // Check if abstract is accepted
        $abstract = $db->table('abstracts')
            ->where('registration_id', $registrationId)
            ->where('review_status', 'accepted')
            ->get()->getFirstRow('array');
            
        return !empty($payment) && !empty($abstract);
    }

    /**
     * Generate LOA HTML content
     */
    private function generateLoaHtml($registration, $abstract, $loaNumber)
    {
        $html = '
        <!DOCTYPE html>
        <html>
        <head>
            <meta charset="UTF-8">
            <title>Letter of Acceptance - ' . $loaNumber . '</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }
                .header { text-align: center; margin-bottom: 40px; }
                .logo { font-size: 24px; font-weight: bold; color: #2c3e50; }
                .title { font-size: 18px; margin-top: 10px; }
                .info-table { width: 100%; border-collapse: collapse; margin: 20px 0; }
                .info-table td { padding: 8px; border: 1px solid #ddd; }
                .signature { margin-top: 50px; }
                .footer { margin-top: 30px; font-size: 12px; color: #666; }
            </style>
        </head>
        <body>
            <div class="header">
                <div class="logo">SNIA CONFERENCE</div>
                <div class="title">Letter of Acceptance</div>
                <div>LOA Number: ' . $loaNumber . '</div>
            </div>
            
            <div class="content">
                <p>Date: ' . date('F d, Y') . '</p>
                
                <p>Dear ' . $registration['first_name'] . ' ' . $registration['last_name'] . ',</p>
                
                <p>We are pleased to inform you that your abstract submission has been <strong>ACCEPTED</strong> for presentation at the ' . $registration['event_title'] . '.</p>
                
                <table class="info-table">
                    <tr><td><strong>Presenter Name</strong></td><td>' . $registration['first_name'] . ' ' . $registration['last_name'] . '</td></tr>
                    <tr><td><strong>Email</strong></td><td>' . $registration['email'] . '</td></tr>
                    <tr><td><strong>Affiliation</strong></td><td>' . ($registration['affiliation'] ?: 'Not specified') . '</td></tr>
                    <tr><td><strong>Event</strong></td><td>' . $registration['event_title'] . '</td></tr>
                    <tr><td><strong>Event Date</strong></td><td>' . date('F d, Y', strtotime($registration['start_date'])) . ' - ' . date('F d, Y', strtotime($registration['end_date'])) . '</td></tr>
                    <tr><td><strong>Location</strong></td><td>' . $registration['location'] . '</td></tr>';
        
        if ($abstract) {
            $html .= '<tr><td><strong>Abstract Title</strong></td><td>' . $abstract['abstract_title'] . '</td></tr>';
        }
        
        $html .= '
                </table>
                
                <p>This letter serves as official confirmation of your acceptance to present at the conference.</p>
                
                <div class="signature">
                    <p>Sincerely,<br><br><strong>SNIA Conference Committee</strong></p>
                </div>
                
                <div class="footer">
                    <p>Generated on ' . date('F d, Y H:i:s') . ' | LOA: ' . $loaNumber . '</p>
                </div>
            </div>
        </body>
        </html>';
        
        return $html;
    }
}
